title: Bisq
url: "https://bisq.network"
markdown: kramdown
permalink: /blog/:title/
livereload: true
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: blog/feed.atom
include:
  - .well-known
  - _redirects
  - _headers
exclude:
  - CNAME
  - README
  - Gemfile
collections:
  dashboard:
    output: true
  proposalcommentaries:
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      en-only: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      en-only: false
paginate: 10
paginate_path: "/blog/page/:num/"
client_version: "1.10.0"
bisq2_version: "2.1.10"
bisqEasyMobile_version: "0.2.1"
bisqConnectMobile_version: "0.2.1"
sass:
  style: compressed
webrick:
  headers:
    Strict-Transport-Security: "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy: "default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; script-src 'self' 'sha256-lwFay0EAIDgMfBfyeJI0mFq40OQvJYWTPQ7FlI6d4RU=' http://127.0.0.1:35729 http://localhost:35729 'sha256-+V3IYVxOlbJ7FRhNmeO46fsYPKBaHqWp/HR7Qvp5TeE=' 'sha256-1JLLuT+/FwQwiREUsrKcMiNbdHf/QzUUjDyjjfnueV4=' 'sha256-26ZTt8HSQ3dqQXZ+/9uEKo+xlEGMOGuwBvwPN68MW6c=' 'sha256-2XkMdFeDrSLLchIiVzCBzs7fQX/jR8EnJuBDLCrjSAE=' 'sha256-3YIO9b/WliPn43dv+K53ob54HQgKetsmETzMvn87i64=' 'sha256-4EirMYjA5EuoJLccZz6D1qPFUTqLA3W+jmcKiKEdD94=' 'sha256-4uTZwfFkqcV+ueLmJ17ND6WfWgi+SDejuSZd/8lx7hY=' 'sha256-78UOAZsk2Z7LPPNjl/ILNJWmvW9TMqIHRtNddVAsbHA=' 'sha256-7BRF3+p8HONLg/DMn0q4t3RN65E1ZjWXrCZLTJa77zI=' 'sha256-94qq0GUIX7UK2dWTZ6h0tvo17J19N5V/AYyBjLAfkyE=' 'sha256-AKceH60IIqPnP/Qzl5wj1J0RTIvjmgikoc3nOSvBfjk=' 'sha256-E4EG0/5gnJwXOi0KJSxra/hQG0Mb43fG6zO4Xr/XqA0=' 'sha256-ETpqqWem/l7sn18bZO+vw+qrxOGDQOwLjCeEXdWVBzE=' 'sha256-EiSBkNO12XvWgAoxx16fUtC4iGOd45n6Ii6VSWVD6Ow=' 'sha256-FFHmyRayk/YB+Hn0KVPuxYVJYESHUcDakvA8fG938ys=' 'sha256-IgudhZDcth5aYLlO4S0JSgysZ3HUbKNP2WwFNJSjlXQ=' 'sha256-J1Z7NqHuVSMM+IoJipeaSunE2MTWpcfZNksPj3h6N9I=' 'sha256-JdpuSnz+abm1yMCEoDAswKwGjm4ZMQFiSUdfa2cnuTY=' 'sha256-N/XQp+FDnrnt03RbUxBYnZjGv4cM1D9b8y5VexnwNRg=' 'sha256-NONerbLFw52iHg80pc3TE5OA01Fm5gT6tKF1+U6QZ+A=' 'sha256-PvDAIh0BqTDHYK2wAfqbSXMob+R+CLCynt4prigWS78=' 'sha256-V9tKlpVAEeNru8y+RM4wHTPib/rDxrYkzsB/EBY5vZU=' 'sha256-VvemWZ2LOwNPVIdvHwPTdmA1m7AN6SpSdLMTsHeukbo=' 'sha256-W6CN9g2baqNmkHsTNmpzjXFm+JhSw56SsHeZD0IFQDw=' 'sha256-Z7mg9Lznr3kvkUZApEXTzPSfE+XokQCruxm+QGP9na4=' 'sha256-aj7yeCGK1O1NlkHr+YNReZYpzc+XvaOQPK5qKWXsa7E=' 'sha256-aoCAKbw466o8cZ2kpMn2BSjBi9wRd/Vs2SxntUpI/U0=' 'sha256-bx0mmjG2X4Ipg8SX6L3Ufwvdz8jyne3G9xRrSZcLvfE=' 'sha256-cAjpZGbngNDWopjbsIE2/Q+hth2WhEUenSFmmlybGsE=' 'sha256-cTHpnId/DThMZ+Rix4Jw6dLADInZ9gpT3maL9pZWdq4=' 'sha256-eTmakajzvtNToh6rolCc4uVbk0sX/QhZNiVZLiLNMYw=' 'sha256-fEUEG8iLRW63gXV0IxFTPDcbi8XxZPnl/mL31cyDba4=' 'sha256-fjYp0/cOhOrmCjhlYt1BzinV9NgV6zjwPJo69NXBn8M=' 'sha256-fraw3Cehd43uScSqnbOm2MJKrGT97Kw0qEQ3aptFUDg=' 'sha256-i76e81HXP4U8Fdqm99EH/owWacab968HbspNKufrSyo=' 'sha256-j97VeQhehmbAvDgKZlgQZ2AgqUCp6cI9m+f+xSnI1XE=' 'sha256-l3tIk0f/O+rL63xVhHCS63LDKfbT2jfQ4W1GA8VIcbU=' 'sha256-ls0Bj6qH+PgbNtNmR+ix+iUIjloEvAvRQGiqpwGM/zo=' 'sha256-m0sqSPovNY55/xk3ZAkmyyW4fZ6UZf4dxyjw+9IoU1Q=' 'sha256-mecI4t7X5sjmM/znpooHc/AzM/uBEYgSSG/4xbMdPr4=' 'sha256-mslBjGwRzadD3zTY0DUa2FXAvSd73SiSTM8EJnMibpw=' 'sha256-ok2im2xRw8fn5KGJmM54VuL+SCM0SE9mftAD05wX11Y=' 'sha256-qGuC55ZCQuZR1kePpgDqvqaP7djZT0n5/9wpwYUqLAc=' 'sha256-svzc8AhZ72TaMR0hxbxpEaUmKMyaMIyGpfX+OG7ocrU=' 'sha256-u9SxSOaZhT/o2PC1Im5GfaJhhjO+3y2YgNoDgF7HokQ=' 'sha256-urLpqAIAzatn6qqB4IlNvAZIX17EHsE03wZJ9T5TdB8=' 'sha256-vsC9zTBSdLDWZvLXIyMN2M9W1xVmgV+PHjgoBVq9o5Y=' 'sha256-xBVaQdLqM2IOogOk1OZN2drwstGp3s0wJmzD5lploVc=' 'sha256-xUKHBL9Xvoax9PT+qbyf3zzDltNNiqyCyQH2dDgXYNQ=' 'sha256-zOT6rgnV2j/UJv1QEeo9dIV+7wWgc1dJTdba8LkTWxc=' 'sha256-zbZ0CUY96AUljFHFeFnUrGURc17kBGgwBZ00gz2MgRE='; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://api.github.com https://bisq.markets https://markets.bisq.services ws://127.0.0.1:35729 ws://localhost:35729; frame-src https://www.youtube-nocookie.com https://www.youtube.com https://player.vimeo.com; form-action 'self' https://bisq.wiki; upgrade-insecure-requests"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"
    X-Frame-Options: "SAMEORIGIN"
