version: "2"

services:
  website:
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
#      - 35729:35729
#      - 3000:3000
#      -   80:4000
    networks:
       - nginx-proxy
networks:
  nginx-proxy:
   external:
      name: nginx-proxy
